isomerpages/moe-nanchiauhigh

_our-one-stop-portals/Parents' One Stop Portal.md
_our-one-stop-portals/Staff's One Stop Portal.md
_our-one-stop-portals/Student's One Stop Portal.md

Update file: Staff's One Stop Portal.md

---

_co-curricular-activities/Clubs and Societies/Green Club.md
_co-curricular-activities/Performing Arts/Wind Orchestra.md

Green Club and Wind Orchestra Edit

---

_co-curricular-activities/Sports and Games/Badminton.md

Update file: Badminton.md

---

_co-curricular-activities/Clubs and Societies/Infocomm Club.md
_co-curricular-activities/Sports and Games/Badminton.md

infocomm and badminton

---

_nchs-highlights/Campus Life@NCHS.md
_nchs-highlights/Celebrating 75 Years of Belonging.md
_nchs-highlights/collection.yml
_our-one-stop-portals/Parents' One Stop Portal.md

Campus Life @ NCHS

---

_our-one-stop-portals/Parents' One Stop Portal.md
_our-student-development/CCE/Sexuality Education.md

Update file: Parents' One Stop Portal.md

---

_our-one-stop-portals/Staff's One Stop Portal.md

…f's One Stop Portal.md","userId":"686"}

Form to Add Questions to Chatbot

---

_our-one-stop-portals/Parents' One Stop Portal.md

…ents' One Stop Portal.md","userId":"686"}

Sec2 Parents e-Engagement

---

_co-curricular-activities/Clubs and Societies/Debate.md
_co-curricular-activities/Uniformed Groups/Scouts.md

Scouts TIC

---

_co-curricular-activities/Clubs and Societies/Infocomm Club.md

Infocomm Club TIC

---

_our-one-stop-portals/Parents' One Stop Portal.md

…ents' One Stop Portal.md","userId":"686"}

Updated DMA Video Guides for Parents

---

_our-one-stop-portals/Student's One Stop Portal.md

…udent's One Stop Portal.md","userId":"686"}

Sec3 EBP 2023

---

_co-curricular-activities/Visual and Performing Arts/Chinese Orchestra.md
_co-curricular-activities/Visual and Performing Arts/String Orchestra.md

Update CO CCA page

---

_co-curricular-activities/Visual and Performing Arts/String Orchestra.md
_our-academic-curriculum/Departments/English Language and Literature.md

SO CCA page

---

_co-curricular-activities/Uniformed Groups/Scouts.md

Scouts CCA info changes

---

_our-one-stop-portals/Admission to NCHS/School Transfer.md

School Transfer

---

_our-one-stop-portals/Admission to NCHS/School Transfer.md

School Transfer 

---

_our-one-stop-portals/Student's One Stop Portal.md

Term 2 Timetable 

---

_co-curricular-activities/Visual and Performing Arts/Wind Orchestra.md

1. Change of name, spelt wrongly: Chiang Wan Ling Angel - remove 'g' from 'Ling'
2. Under 'Achievement', to replace with the following:
Achievements
1. SYF Arts Presentation for Concert Bands (Certificate of Distinction (2025))
2. Asia-Pacific Band Festival 2024 (Gold with Distinction, Champion in Secondary School Division)
3. SYF Arts Presentation for Concert Bands (Certificate of Distinction (2023, 2021, 2019))
4. Singapore International Band Festival (Silver (2022))

Wind Orchestra

---

_co-curricular-activities/Sports and Games/Table Tennis.md

chean_kai_xian_annette@moe.edu.sg
